ALTER TABLE users ADD COLUMN age INTEGER;

UPDATE users SET age = EXTRACT(YEAR FROM AGE(CURRENT_DATE, dob)) WHERE dob IS NOT NULL;

ALTER TABLE users DROP COLUMN dob;

ALTER TABLE users ALTER COLUMN age SET NOT NULL;
